services:
#    sa_atendimento.example:
#        class: SA\AtendimentoBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]

     report.atendimentoanalitico:
          class: SA\AtendimentoBundle\Report\ReportAtendimentoAnalitico
          arguments: ["@service_container"]
#HttpCliente to request Lois Estoque
     http.client:
          class: SA\AtendimentoBundle\HttpClient\HttpClient
          calls:
              - [setUrl, ["%webservice_url%"]]