<?php

namespace SA\AtendimentoBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */

use \Doctrine\ORM\EntityRepository;


class ProdutoRepository extends EntityRepository
{

    public function getProdutoPendente($atendimentoId)
    {
        return $this->getEntityManager()
            ->createQuery("SELECT p
                           FROM SAAtendimentoBundle:Produto p
                           WHERE p.status != 3
                           AND p.atendimento = :atendimento")
            ->setParameter('atendimento',$atendimentoId)
            ->getResult();

    }

}
